### ISSUE TITLE
App Wireframe

### ISSUE THREAD

**Issue by thuymymai** [thuymymai/Helpers#1]
Link to figma: [link](https://www.figma.com/file/5xiehFlwQHWJerr1WPHVoM/Untitled?node-id=0%3A1)

**Comment by anniekuusinen** [comment]
https://www.figma.com/file/j2c4EIft4kh8LcCiCZeqgD/Brainstorming-sketch

**Comment by thuymymai** [comment]
Inspiration: [https://dribbble.com/shots/14459621-Callert-Life-saving-app-concept/attachments/6142188?mode=media](https://dribbble.com/shots/14459621-Callert-Life-saving-app-concept/attachments/6142188?mode=media)

**Comment by anniekuusinen** [comment]
https://dribbble.com/shots/11486146-Wheelmate-s

**Comment by thuymymai** [comment]
Colors: [https://dribbble.com/shots/5815838-VoiceBanking-App-Concept](https://dribbble.com/shots/5815838-VoiceBanking-App-Concept)

**Comment by thuymymai** [comment]
[https://www.behance.net/gallery/105647943/Callert-life-saving-procedures-digitized%E2%80%9D%20rel=](https://www.behance.net/gallery/105647943/Callert-life-saving-procedures-digitized%E2%80%9D%20rel=)

**Comment by thuymymai** [comment]
Color code
primary 1: 3C4FB6
primary 2: EBEFF7
background: FCFCFC
text_primary: 010101
text_light: ABAEBC
other: F6FBFF
