### ISSUE TITLE
Data for fetching from network

### ISSUE THREAD

**Issue by thuymymai** [thuymymai/Helpers#17]
Data in different languages?

**Comment by thuymymai** [comment]
Link to draft 1: [Link](https://docs.google.com/spreadsheets/d/1I0byQfKL9Q_9hEYdjOnpByFx8vtTOV6FLtXg_3JP7QQ/edit?usp=sharing)

**Comment by minhson0506** [comment]
Edited data and move to  [google driver](https://docs.google.com/spreadsheets/d/13RKipw0Rp2FqB3lPYiKMe-atsZ35f9JbYKZwPlAVqBg/edit#gid=397035638)
When you edit data, please inform me and I will update the data in network

Now, I create only user data in network to test login and sign up first: 
[User data](https://users.metropolia.fi/~sond/Swift%20Project/user.json)
[Task data](https://users.metropolia.fi/~sond/Swift%20Project/task.json)
