### ISSUE TITLE
Design Sprint features test

### ISSUE THREAD

**Issue by anniekuusinen** [thuymymai/Helpers#4]
1. Create a finding template 

2. Create prototype on features to be tested

- [x] Emergency feature
- [x] Non urgent help
- [x] register volunteer user
- [x] App flow in volunteer task manager

3. Test prototype on features and update document Research findings

- [x] Emergency feature
- [x] Non urgent help
- [x] register volunteer user
- [x] App flow in volunteer task manager

Documents:
[Research Planning](https://docs.google.com/document/d/1pYynxwkmtjr6ppws2LAEvARfN11r4XcHjRmUAWv0kQo/edit)
[Research findings](https://docs.google.com/spreadsheets/d/1GmjEZ-79ekeNT3zjVUc_o58yYNaGt8yzKVyNkvOowGI/edit#gid=0)

**Comment by anniekuusinen** [comment]
Prototype done for volunteer testing scenarios.[ Link to prototype (flow 1 + flow 2)](https://www.figma.com/proto/5xiehFlwQHWJerr1WPHVoM/Helpers?node-id=82%3A69&scaling=scale-down&page-id=80%3A68&starting-point-node-id=82%3A69&show-proto-sidebar=1)

**Comment by thuymymai** [comment]
Prototype done for help seeker testing scenarios: [Link to prototype](https://www.figma.com/file/5xiehFlwQHWJerr1WPHVoM/Helpers?node-id=12%3A2)
