### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by thuymymai** [thuymymai/Helpers#70]
Final presentation ppt: [here](https://docs.google.com/presentation/d/1P0hN9MADRDIjHaLYzW_44nMdM0eZ8UW8dr1weMCCPMI/edit?usp=sharing)
Demo: [video](https://drive.google.com/file/d/1C7cxOpepkTYQZKaSI48AgsOCjYe7V0NW/view?usp=sharing)

**Comment by minhson0506** [comment]
Video demo with call and message function in real phone (iPhone X 15.4)
[Video](https://drive.google.com/file/d/14k7wPMF68QCDqngj8w1iHuiBH4fSUV3S/view?usp=sharing)
